export const videoGamesCollectionMiddle = [
	{
		_id: "1eldenRingMiddle77",
		title: "Elden Ring",
		rate: 9.0,
		imageMiddle: "eldenRingMiddle.jpg",
		altImageMiddle: "Девушка из Elden Ring в рыцарских доспехах сидит на коленках",
		tags: ["Открытый мир", "RPG", "Ролевой боевик", "Приключения"],
		price: 3999,
		platform: ["windows.svg"],
		iconForTitle: "warriorHelmet.svg",
		iconForTitleAlt: "Шлем воина",
		subTitle: "На тропе войны"
	},
	{
		_id: "2dota2lol56",
		title: "Dota 2",
		rate: 9.1,
		imageMiddle: "dota2Middle.jpg",
		altImageMiddle: "Пудж (персонаж из игры) в крови",
		tags: ["MOBA", "Развлечение", "Фэнтези", "action", "RPG", "Спекулятивная фантастика", "Societal"],
		price: "играй бесплатно",
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "dota2.svg",
		iconForTitleAlt: "Иконка игры Dota 2",
		subTitle: "Сражение - это зрелищно"
	},
	{
		_id: "3atomicHeart564",
		title: "Atomic Heart",
		rate: 9.5,
		imageMiddle: "atomicHeartMiddle.jpg",
		altImageMiddle: "Главный герой игры с дубиной на плече",
		tags: ["Шутер", "action", "RPG", "Файтинг", "Action-adventure", "Приключения"],
		price: "ожидание",
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "robot.svg",
		iconForTitleAlt: "Иконка робота",
		subTitle: "У них есть душа?"
	},
	{
		_id: "4theDayBefore9567",
		title: "The Day Before",
		rate: 8.5,
		imageMiddle: "theDayBeforeMiddle.jpg",
		altImageMiddle: "Половина лица главного героя, он стоит с автоматом на плече",
		tags: ["Шутер", "action", "Action-adventure", "Приключения"],
		price: "ожидание",
		platform: ["windows.svg", "apple.svg", "playstation.svg", "xboxOne.svg"],
		iconForTitle: "survival.svg",
		iconForTitleAlt: "Иконка черепа в огне",
		subTitle: "Выжить любой ценой"
	},
	{
		_id: "5enlisted8776",
		title: "Enlisted",
		rate: 8.0,
		imageMiddle: "enlistedMiddle.jpg",
		altImageMiddle: "Советский солдат целится",
		tags: ["Шутер", "action", "Симулятор"],
		price: "играй бесплатно",
		platform: ["windows.svg", "playstation.svg", "xboxOne.svg"],
		iconForTitle: "war.svg",
		iconForTitleAlt: "Советские солдаты устанавливают знамя",
		subTitle: "Фронт не ждет!"
	},
	{
		_id: "6beholder3lfdg8776",
		title: "Beholder 3",
		rate: 8.8,
		imageMiddle: "beholder3Middle.jpeg",
		altImageMiddle: "Персонаж из игры стоит на балконе своего дома",
		tags: ["стратегия", "Симулятор"],
		price: 360,
		platform: ["windows.svg"],
		iconForTitle: "peoples.svg",
		iconForTitleAlt: "Иконка на которой изображены 3 политика",
		subTitle: "Влияние и манипуляция"
	},
	{
		_id: "7lostArk8776",
		title: "Lost ARK",
		rate: 8.3,
		imageMiddle: "lostArkMiddle.jpg",
		altImageMiddle: "Персонаж-девушка из игры",
		tags: ["action", "MMORPG"],
		price: "играй бесплатно",
		platform: ["windows.svg"],
		iconForTitle: "magicStaff.svg",
		iconForTitleAlt: "Магический посох",
		subTitle: "Дивный мир"
	},
	{
		_id: "8godOfWar8776",
		title: "God Of War",
		rate: 7.1,
		imageMiddle: "godOfWarMiddle.jpg",
		altImageMiddle: "Кратос",
		tags: ["Action-adventure", "hack and slash"],
		price: 2500,
		platform: ["windows.svg"],
		iconForTitle: "axe.svg",
		iconForTitleAlt: "Секира Кратоса",
		subTitle: "Кратос на тропе войны"
	},
	{
		_id: "9dlsh84545",
		title: "Dying Light 2 Stay Human",
		rate: 6.4,
		imageMiddle: "dyingLight2Middle.jpg",
		altImageMiddle: "Главный персонаж из игры стоит на кране",
		tags: ["action", "RPG", "survival horror"],
		price: 3500,
		platform: ["windows.svg"],
		iconForTitle: "zombie.svg",
		iconForTitleAlt: "Голова зомби",
		subTitle: "Двигайся!"
	},
	{
		_id: "10gta5jkjh84545",
		title: "Grand theft auto 5",
		rate: 8.0,
		imageMiddle: "gta5Middle.jpg",
		altImageMiddle: "3 главных персонажа стоят на горе",
		tags: ["action-adventure"],
		price: 1777,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "gta5.svg",
		iconForTitleAlt: "Логотип GTA 5",
		subTitle: "Деньги, как смысл жизни"
	},
	{
		_id: "11theWither5jkjh84545",
		title: "The Witcher",
		rate: 9.4,
		imageMiddle: "witcherMiddle.jpg",
		altImageMiddle: "Ведьмак с отрубленными головами монстров",
		tags: ["Открытый мир", "action", "RPG", "Файтинг", "Action-adventure", "Нелинейность", "multi-colophon"],
		price: 3400,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "witcher.svg",
		iconForTitleAlt: "Голова волка",
		subTitle: "Освободи земли от демонов"
	},
	{
		_id: "1276853star",
		title: "Starcraft 2: Legacy of the void",
		rate: 8.4,
		imageMiddle: "starCraftMiddle.jpg",
		altImageMiddle: "Персонаж из игры на горе в готовности к битве",
		tags: ["стратегия", "action"],
		price: 1649,
		platform: ["windows.svg"],
		iconForTitle: "nlo.svg",
		iconForTitleAlt: "Голова инопланетянина",
		subTitle: "Чувствую битву"
	},
	{
		_id: "1356756",
		title: "Aperture Desk Job",
		rate: 6.5,
		imageMiddle: "apertureMiddle.jpg",
		altImageMiddle: "Схема туалета и сам туалет из игры",
		tags: ["Приключения"],
		price: "играй бесплатно",
		platform: ["windows.svg"],
		iconForTitle: "pipe.svg",
		iconForTitleAlt: "Трубы",
		subTitle: "Мастери и помни, главное смекалка"
	},
	{
		_id: "14farChanging43534",
		title: "FAR: Changing Tides",
		rate: 6.4,
		imageMiddle: "farMiddle.jpeg",
		altImageMiddle: "Развалины, обломки",
		tags: ["Приключения"],
		price: 480,
		platform: ["windows.svg"],
		iconForTitle: "ship.svg",
		iconForTitleAlt: "Штурвал корабля",
		subTitle: "Приключения зовут"
	},
	{
		_id: "156786878rtyrtfghfhg",
		title: "Conan Chop Chop",
		rate: 5.5,
		imageMiddle: "conanMiddle.jpeg",
		altImageMiddle: "Викинг сражается с противником",
		tags: ["Приключения", "RPG", "action"],
		price: 520,
		platform: ["windows.svg"],
		iconForTitle: "viking.svg",
		iconForTitleAlt: "Шлем викинга",
		subTitle: "Время побеждать"
	},
	{
		_id: "16alloda54646mbn",
		title: "АЛЛОДЫ Онлайн",
		rate: 9.6,
		imageMiddle: "allodsMiddle.jpg",
		altImageMiddle: "Герои игры передвигаются на летающем корабле",
		tags: ["Ролевая игра", "RPG", "action"],
		price: "играй бесплатно",
		platform: ["windows.svg"],
		iconForTitle: "luchi.svg",
		iconForTitleAlt: "Лучи, звездочки",
		subTitle: "Погрузись в Аллоды"
	},
	{
		_id: "17warface54646mbn",
		title: "Warface",
		rate: 9.5,
		imageMiddle: "warfaceMiddle.jpg",
		altImageMiddle: "3 солдата из игры warface",
		tags: ["Action-adventure", "Шутер", "action", "Приключения"],
		price: "играй бесплатно",
		platform: ["windows.svg", "xboxOne.svg", "playstation.svg"],
		iconForTitle: "gun.svg",
		iconForTitleAlt: "Пистолет",
		subTitle: "Вступай в команду Warface"
	},
	{
		_id: "18ill54646mbn",
		title: "ILL",
		rate: 9.2,
		imageMiddle: "illMiddle.jpg",
		altImageMiddle: "Персонажа тащат за ноги",
		tags: ["Хоррор", "Шутер", "action", "Приключения"],
		price: "ожидание",
		platform: ["windows.svg"],
		iconForTitle: "handZombie.svg",
		iconForTitleAlt: "Рука зомби из земли",
		subTitle: "Не оборачивайся!!!"
	},
	{
		_id: "19pioner54646mbn",
		title: "Pioner",
		rate: 9.4,
		imageMiddle: "pionerMiddle.jpeg",
		altImageMiddle: "Девушка и мужчина сражаются с монстрами",
		tags: ["Постапокалипсис", "Шутер", "action", "Приключения", "Выживание"],
		price: "ожидание",
		platform: ["windows.svg", "xboxOne.svg", "playstation.svg"],
		iconForTitle: "blowHeadZombie.svg",
		iconForTitleAlt: "Человек бьет зомби по голове",
		subTitle: "Мы должны выжить на этой земле"
	},
	{
		_id: "20tbunny567567",
		title: "Tiny Bunny",
		rate: 7.6,
		imageMiddle: "tinyBunnyMiddle.jpg",
		altImageMiddle: "Заяц",
		tags: ["Хоррор", "Приключения"],
		price: 299,
		platform: ["windows.svg"],
		iconForTitle: "hare.svg",
		iconForTitleAlt: "Голова зайца",
		subTitle: "Зайчик, зайчик попрыгайчик..."
	},
	{
		_id: "21spark567gfhfg",
		title: "SPARK in the Dark",
		rate: 8.8,
		imageMiddle: "sparkInTheDarkMiddle.jpg",
		altImageMiddle: "Логотип игры",
		tags: ["Action-adventure", "Приключения", "Ролевая игра", "action", "Демоверсии"],
		price: "играй бесплатно",
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "spider.svg",
		iconForTitleAlt: "Паук",
		subTitle: "Подземелья таят невероятную угрозу"
	},
	{
		_id: "21spark567gfhfggcsgo90",
		title: "CS:GO PRIME STATUS UPGRADE",
		rate: 7.1,
		imageMiddle: "csgoMiddle.jpg",
		altImageMiddle: "Логотип игры cs:go",
		tags: ["Шутер", "action"],
		price: 1020,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "soldier.svg",
		iconForTitleAlt: "Солдат",
		subTitle: "Пора ринуться в бой"
	},
	{
		_id: "21spark567gfhfgmonster8",
		title: "Monster Hunter Rise",
		rate: 6.4,
		imageMiddle: "monsterHunterRiseMiddle.jpg",
		altImageMiddle: "Чудовище из игры набрасывается с открытой пастью",
		tags: ["action"],
		price: 2299,
		platform: ["windows.svg"],
		iconForTitle: "monsterHead.svg",
		iconForTitleAlt: "Голова монстра",
		subTitle: "Готов ли ты сразиться?"
	},
	{
		_id: "21spark567gfhfgdetroit9090",
		title: "Detroit: Become Human",
		rate: 9.1,
		imageMiddle: "detroitBecomeHumanMiddle.jpg",
		altImageMiddle: "Главный герой из игры",
		tags: ["Фэнтези", "Приключения", "action"],
		price: 1628,
		platform: ["windows.svg"],
		iconForTitle: "chipBrain.svg",
		iconForTitleAlt: "Мозг робота - чип",
		subTitle: "Возможно стать человеком..."
	},
	{
		_id: "21spark567gfhfgdayzzzzzzz",
		title: "DayZ",
		rate: 9.4,
		imageMiddle: "dayzMiddle.jpg",
		altImageMiddle: "Выживший стоит на дороге",
		tags: ["Выживание", "Шутер", "action", "Постапокалипсис"],
		price: 877,
		platform: ["windows.svg"],
		iconForTitle: "zombieHead.svg",
		iconForTitleAlt: "Голова зомби",
		subTitle: "О! Враждебный мир"
	},
	{
		_id: "21spark567gfhfgmadisonhor",
		title: "MADiSON",
		rate: 0.0,
		imageMiddle: "madisonMiddle.jpeg",
		altImageMiddle: "Рука чудовища над фотоаппаратом",
		tags: ["Психологический хоррор", "Хоррор", "Хоррор на выживание"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "ghost.svg",
		iconForTitleAlt: "Чудовище в халате",
		subTitle: "Не включай вспышку!"
	},
	{
		_id: "21spark567gfhfyoungiiiii",
		title: "Young Souls",
		rate: 0.0,
		imageMiddle: "youngSoulsMiddle.jpg",
		altImageMiddle: "Постер игры: главные герои и враги за их спинами",
		tags: ["action", "RPG"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "hero.svg",
		iconForTitleAlt: "Иконка героя",
		subTitle: "Стань борцом за справедливость"
	},
	{
		_id: "21spark567gfhfhyperbolica546",
		title: "HYPERBOLICA",
		rate: 0.0,
		imageMiddle: "hyperbolicaMiddle.jpeg",
		altImageMiddle: "Мир hyperbolica",
		tags: ["Фэнтези", "Приключения", "Логическая"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg", "vr.svg"],
		iconForTitle: "abstractionCube.svg",
		iconForTitleAlt: "Иконка абстрактного куба",
		subTitle: "Мир чудес"
	},
	{
		_id: "21spark567gfhfdistantworld435",
		title: "Distant Worlds 2",
		rate: 0.0,
		imageMiddle: "distantWorlds2Middle.jpg",
		altImageMiddle: "Космическая битва",
		tags: ["Симулятор", "стратегия"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "spacePlants.svg",
		iconForTitleAlt: "Планеты в космосе",
		subTitle: "Борозди просторы и укрепи альянс"
	},
	{
		_id: "21spark567ruin",
		title: "RUiN",
		rate: 0.0,
		imageMiddle: "ruinMiddle.jpg",
		altImageMiddle: "Персонаж из игры передвигается по карте",
		tags: ["MOBA", "стратегия"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "moba.svg",
		iconForTitleAlt: "Иконка специфики MOBA - карта",
		subTitle: "Арена ждет тебя!"
	}
]

export default function getGamesCollectionMiddle() {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve(videoGamesCollectionMiddle)
		}, 1500)
	})
}