export const videoGamesCollectionMiddle = [
	{
		_id: "21spark567magica2dfg675",
		title: "Magicka 2",
		rate: 9.5,
		country: "SE",
		imageMiddle: "magica2Middle.jpg",
		altImageMiddle: "Главные герои в кругу обороняются от врагов",
		tags: ["Приключения", "action"],
		price: 87,
		oldPrice: 349,
		sale: 75,
		platform: ["windows.svg", "linux.svg", "apple.svg"],
		iconForTitle: "magic.svg",
		iconForTitleAlt: "Рука мага",
		subTitle: "Комбинация Жизни и Смерти",
		aboutUsGames: { path: "magicka2.jpg", alt: "Маг из игры сражается в красном плаще" }
	},
	{
		_id: "1eldenRingMiddle77",
		title: "Elden Ring",
		rate: 9.4,
		country: "JP",
		imageMiddle: "eldenRingMiddle.jpg",
		altImageMiddle: "Девушка из Elden Ring в рыцарских доспехах сидит на коленках",
		tags: ["Открытый мир", "RPG", "Ролевой боевик", "Приключения"],
		price: 3999,
		platform: ["windows.svg"],
		iconForTitle: "warriorHelmet.svg",
		iconForTitleAlt: "Шлем воина",
		subTitle: "На тропе войны",
		aboutUsGames: { path: "eldenRing.jpg", alt: "Логотип Elden Ring" }
	},
	{
		_id: "2dota2lol56",
		title: "Dota 2",
		rate: 9.1,
		country: "US",
		imageMiddle: "dota2Middle.jpg",
		altImageMiddle: "Пудж (персонаж из игры) в крови",
		tags: ["MOBA", "Развлечение", "Фэнтези", "action", "RPG", "Спекулятивная фантастика", "Societal"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg", "apple.svg", "linux.svg"],
		iconForTitle: "dota2.svg",
		iconForTitleAlt: "Иконка игры Dota 2",
		subTitle: "Сражение - это зрелищно",
		aboutUsGames: { path: "dota2.jpg", alt: "Логотип Dota 2" }
	},
	{
		_id: "21spark567gamedec",
		title: "Gamedec",
		rate: 7.3,
		country: "PL",
		imageMiddle: "gamedecMiddle.jpg",
		altImageMiddle: "Главный герой на фоне города",
		tags: ["RPG", "Приключения"],
		price: 936,
		oldPrice: 1249,
		sale: 25,
		platform: ["windows.svg"],
		iconForTitle: "cyberpunkWoman.svg",
		iconForTitleAlt: "Девушка с прядью волос",
		subTitle: "Технический нуар",
		aboutUsGames: { path: "gamedec.jpg", alt: "3 персонажа из игры Gamedec, мужчина с бородой и железной рукой, бизнесмен, девушка" }
	},
	{
		_id: "3atomicHeart564",
		title: "Atomic Heart",
		rate: 9.5,
		country: "RU",
		imageMiddle: "atomicHeartMiddle.jpg",
		altImageMiddle: "Главный герой игры с дубиной на плече",
		tags: ["Шутер", "action", "RPG", "Файтинг", "Action-adventure", "Приключения"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "robot.svg",
		iconForTitleAlt: "Иконка робота",
		subTitle: "У них есть душа?",
		aboutUsGames: { path: "atomicHeart.jpg", alt: "Логотип Atomic Heart" }
	},
	{
		_id: "4theDayBefore9567",
		title: "The Day Before",
		rate: 8.5,
		country: "RU",
		imageMiddle: "theDayBeforeMiddle.jpg",
		altImageMiddle: "Половина лица главного героя, он стоит с автоматом на плече",
		tags: ["Шутер", "action", "Action-adventure", "Приключения"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg", "apple.svg", "playstation.svg", "xboxOne.svg"],
		iconForTitle: "survival.svg",
		iconForTitleAlt: "Иконка черепа в огне",
		subTitle: "Выжить любой ценой",
		aboutUsGames: { path: "theDayBefore.jpg", alt: "Логотип The Day Before" }
	},
	{
		_id: "5enlisted8776",
		title: "Enlisted",
		rate: 8.0,
		country: "RU",
		imageMiddle: "enlistedMiddle.jpg",
		altImageMiddle: "Советский солдат целится",
		tags: ["Шутер", "action", "Симулятор"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg", "playstation.svg", "xboxOne.svg"],
		iconForTitle: "war.svg",
		iconForTitleAlt: "Советские солдаты устанавливают знамя",
		subTitle: "Фронт не ждет!",
		aboutUsGames: { path: "enlisted.jpg", alt: "Солдат СССР, а за стеной фашист" }
	},
	{
		_id: "6beholder3lfdg8776",
		title: "Beholder 3",
		rate: 8.8,
		country: "RU",
		imageMiddle: "beholder3Middle.jpeg",
		altImageMiddle: "Персонаж из игры стоит на балконе своего дома",
		tags: ["стратегия", "Симулятор"],
		price: 360,
		platform: ["windows.svg"],
		iconForTitle: "peoples.svg",
		iconForTitleAlt: "Иконка на которой изображены 3 политика",
		subTitle: "Влияние и манипуляция",
		aboutUsGames: { path: "beholder3poster.jpg", alt: "Логотип Beholder 3" }
	},
	{
		_id: "7lostArk8776",
		title: "Lost ARK",
		rate: 8.3,
		country: "RU",
		imageMiddle: "lostArkMiddle.jpg",
		altImageMiddle: "Персонаж-девушка из игры",
		tags: ["action", "MMORPG"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg"],
		iconForTitle: "magicStaff.svg",
		iconForTitleAlt: "Магический посох",
		subTitle: "Дивный мир",
		aboutUsGames: { path: "lostArk.jpg", alt: "Персонаж из игры LOSTARK" }
	},
	{
		_id: "21spark567r435emnant",
		title: "Remnant: From The Ashes",
		rate: 6.3,
		country: "US",
		imageMiddle: "remnantFromTheAshes.jpg",
		altImageMiddle: "Главный герой на переднем плане, вдали виднеются монстры",
		tags: ["Шутер", "action", "Приключения"],
		price: 518,
		oldPrice: 1297,
		sale: 60,
		platform: ["windows.svg", "xboxOne.svg", "playstation.svg"],
		iconForTitle: "rat.svg",
		iconForTitleAlt: "Крыса",
		subTitle: "Дай ЖАРУ",
		aboutUsGames: { path: "remnant.png", alt: "Главного героя игры опутали щупальцами монстры" }
	},
	{
		_id: "8godOfWar8776",
		title: "God Of War",
		rate: 7.1,
		country: "US",
		imageMiddle: "godOfWarMiddle.jpg",
		altImageMiddle: "Кратос",
		tags: ["Action-adventure", "hack and slash"],
		price: 2500,
		platform: ["windows.svg"],
		iconForTitle: "axe.svg",
		iconForTitleAlt: "Секира Кратоса",
		subTitle: "Кратос на тропе войны",
		aboutUsGames: { path: "godOfWar.jpg", alt: "Логотип God of War" }
	},
	{
		_id: "9dlsh84545",
		title: "Dying Light 2 Stay Human",
		rate: 6.4,
		country: "PL",
		imageMiddle: "dyingLight2Middle.jpg",
		altImageMiddle: "Главный персонаж из игры стоит на кране",
		tags: ["action", "RPG", "survival horror"],
		price: 3500,
		platform: ["windows.svg"],
		iconForTitle: "zombie.svg",
		iconForTitleAlt: "Голова зомби",
		subTitle: "Двигайся!",
		aboutUsGames: { path: "dyingLinght2StayHuman.jpg", alt: "Логотип Dying Linght 2 Stay Human" }
	},
	{
		_id: "10gta5jkjh84545",
		title: "Grand theft auto 5",
		rate: 8.0,
		country: "US",
		imageMiddle: "gta5Middle.jpg",
		altImageMiddle: "3 главных персонажа стоят на горе",
		tags: ["action-adventure"],
		price: 1777,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "gta5.svg",
		iconForTitleAlt: "Логотип GTA 5",
		subTitle: "Деньги, как смысл жизни",
		aboutUsGames: { path: "gta5.png", alt: "Логотип GTA 5" }
	},
	{
		_id: "11theWither5jkjh84545",
		title: "The Witcher",
		rate: 9.0,
		country: "PL",
		imageMiddle: "witcherMiddle.jpg",
		altImageMiddle: "Ведьмак с отрубленными головами монстров",
		tags: ["Открытый мир", "action", "RPG", "Файтинг", "Action-adventure", "Нелинейность", "multi-colophon"],
		price: 3400,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "witcher.svg",
		iconForTitleAlt: "Голова волка",
		subTitle: "Освободи земли от демонов",
		aboutUsGames: { path: "theWitcher.jpg", alt: "Логотип Ведьмак 3" }
	},
	{
		_id: "1276853star",
		title: "Starcraft 2: Legacy of the void",
		rate: 8.4,
		country: "US",
		imageMiddle: "starCraftMiddle.jpg",
		altImageMiddle: "Персонаж из игры на горе в готовности к битве",
		tags: ["стратегия", "action"],
		price: 1649,
		platform: ["windows.svg"],
		iconForTitle: "nlo.svg",
		iconForTitleAlt: "Голова инопланетянина",
		subTitle: "Чувствую битву",
		aboutUsGames: { path: "starcraft2LegacyOfTheVoid.jpg", alt: "Логотип Starcraft 2 Legacy Of The Void" }
	},
	{
		_id: "21spark567batlearenafdgdfg000",
		title: "Battle Brothers",
		rate: 4.3,
		country: "DE",
		imageMiddle: "battleBrothersMiddle.jpg",
		altImageMiddle: "Воин сражается с нежетью",
		tags: ["RPG", "стратегия"],
		price: 164,
		oldPrice: 499,
		sale: 67,
		platform: ["windows.svg"],
		iconForTitle: "crossedSwords.svg",
		iconForTitleAlt: "Перекрещенные мечи",
		subTitle: "Биться во имя света",
		aboutUsGames: { path: "battleBrothers.jpg", alt: "Логотип Battle Brothers" }
	},
	{
		_id: "1356756",
		title: "Aperture Desk Job",
		rate: 6.5,
		country: "US",
		imageMiddle: "apertureMiddle.jpg",
		altImageMiddle: "Схема туалета и сам туалет из игры",
		tags: ["Приключения"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg"],
		iconForTitle: "pipe.svg",
		iconForTitleAlt: "Трубы",
		subTitle: "Мастери и помни, главное смекалка",
		aboutUsGames: { path: "apertureDeskJob.jpg", alt: "Логотип Aperture Desk Job" }
	},
	{
		_id: "14farChanging43534",
		title: "FAR: Changing Tides",
		rate: 6.4,
		country: "CH",
		imageMiddle: "farMiddle.jpeg",
		altImageMiddle: "Развалины, обломки",
		tags: ["Приключения"],
		price: 480,
		platform: ["windows.svg"],
		iconForTitle: "ship.svg",
		iconForTitleAlt: "Штурвал корабля",
		subTitle: "Приключения зовут",
		aboutUsGames: { path: "farChangingTides.jpg", alt: "FAR: Changing Tides" }
	},
	{
		_id: "156786878rtyrtfghfhg",
		title: "Conan Chop Chop",
		rate: 5.5,
		country: "AU",
		imageMiddle: "conanMiddle.jpeg",
		altImageMiddle: "Викинг сражается с противником",
		tags: ["Приключения", "RPG", "action"],
		price: 520,
		platform: ["windows.svg"],
		iconForTitle: "viking.svg",
		iconForTitleAlt: "Шлем викинга",
		subTitle: "Время побеждать",
		aboutUsGames: { path: "conanChopChop.jpg", alt: "Conan Chop Chop" }
	},
	{
		_id: "16alloda54646mbn",
		title: "АЛЛОДЫ Онлайн",
		rate: 9.6,
		country: "RU",
		imageMiddle: "allodsMiddle.jpg",
		altImageMiddle: "Герои игры передвигаются на летающем корабле",
		tags: ["Ролевая игра", "RPG", "action"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg"],
		iconForTitle: "luchi.svg",
		iconForTitleAlt: "Лучи, звездочки",
		subTitle: "Погрузись в Аллоды",
		aboutUsGames: { path: "alloda.jpg", alt: "Логотип Аллоды Онлайн" }
	},
	{
		_id: "17warface54646mbn",
		title: "Warface",
		rate: 9.5,
		country: "RU",
		imageMiddle: "warfaceMiddle.jpg",
		altImageMiddle: "3 солдата из игры warface",
		tags: ["Action-adventure", "Шутер", "action", "Приключения"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg", "xboxOne.svg", "playstation.svg"],
		iconForTitle: "gun.svg",
		iconForTitleAlt: "Пистолет",
		subTitle: "Вступай в команду Warface",
		aboutUsGames: { path: "warface.jpg", alt: "Логотип Warface" }
	},
	{
		_id: "18ill54646mbn",
		title: "ILL",
		rate: 9.2,
		country: "RU",
		imageMiddle: "illMiddle.jpg",
		altImageMiddle: "Персонажа тащат за ноги",
		tags: ["Хоррор", "Шутер", "action", "Приключения"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "handZombie.svg",
		iconForTitleAlt: "Рука зомби из земли",
		subTitle: "Не оборачивайся!!!",
		aboutUsGames: { path: "ill.jpg", alt: "Логотип ILL (отечественный хоррор)" }
	},
	{
		_id: "19pioner54646mbn",
		title: "Pioner",
		rate: 9.4,
		country: "RU",
		imageMiddle: "pionerMiddle.jpeg",
		altImageMiddle: "Девушка и мужчина сражаются с монстрами",
		tags: ["Постапокалипсис", "Шутер", "action", "Приключения", "Выживание"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg", "xboxOne.svg", "playstation.svg"],
		iconForTitle: "blowHeadZombie.svg",
		iconForTitleAlt: "Человек бьет зомби по голове",
		subTitle: "Мы должны выжить на этой земле",
		aboutUsGames: { path: "pioner.jpg", alt: "Логотип Pioner" }
	},
	{
		_id: "20tbunny567567",
		title: "Tiny Bunny",
		rate: 7.6,
		country: "RU",
		imageMiddle: "tinyBunnyMiddle.jpg",
		altImageMiddle: "Заяц",
		tags: ["Хоррор", "Приключения"],
		price: 299,
		platform: ["windows.svg"],
		iconForTitle: "hare.svg",
		iconForTitleAlt: "Голова зайца",
		subTitle: "Зайчик, зайчик попрыгайчик...",
		aboutUsGames: { path: "tinyBunny.jpg", alt: "Логотип Зайчик" }
	},
	{
		_id: "21spark567gfhfg",
		title: "SPARK in the Dark",
		rate: 8.8,
		country: "RU",
		imageMiddle: "sparkInTheDarkMiddle.jpg",
		altImageMiddle: "Логотип игры",
		tags: ["Action-adventure", "Приключения", "Ролевая игра", "action", "Демоверсии"],
		price: 0,
		textPrice: "играй бесплатно",
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "spider.svg",
		iconForTitleAlt: "Паук",
		subTitle: "Подземелья таят невероятную угрозу",
		aboutUsGames: { path: "sparkInTheDark.jpg", alt: "Логотип Spark In The Dark" }
	},
	{
		_id: "21spark567gfhfggcsgo90",
		title: "CS:GO PRIME STATUS UPGRADE",
		rate: 7.1,
		country: "US",
		imageMiddle: "csgoMiddle.jpg",
		altImageMiddle: "Логотип игры cs:go",
		tags: ["Шутер", "action"],
		price: 1020,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "soldier.svg",
		iconForTitleAlt: "Солдат",
		subTitle: "Пора ринуться в бой",
		aboutUsGames: { path: "csGO.jpg", alt: "CS:GO" }
	},
	{
		_id: "21spark567gfhfgmonster8",
		title: "Monster Hunter Rise",
		rate: 6.4,
		country: "JP",
		imageMiddle: "monsterHunterRiseMiddle.jpg",
		altImageMiddle: "Чудовище из игры набрасывается с открытой пастью",
		tags: ["action"],
		price: 1999,
		platform: ["windows.svg"],
		iconForTitle: "monsterHead.svg",
		iconForTitleAlt: "Голова монстра",
		subTitle: "Готов ли ты сразиться?",
		aboutUsGames: { path: "monsterHunterRise.jpg", alt: "Логотип Monster Hunter Rise и монстр из игры" }
	},
	{
		_id: "21spark567gfhfgdetroit9090",
		title: "Detroit: Become Human",
		rate: 9.1,
		country: "FR",
		imageMiddle: "detroitBecomeHumanMiddle.jpg",
		altImageMiddle: "Главный герой из игры",
		tags: ["Фэнтези", "Приключения", "action"],
		price: 1628,
		platform: ["windows.svg"],
		iconForTitle: "chipBrain.svg",
		iconForTitleAlt: "Мозг робота - чип",
		subTitle: "Возможно стать человеком...",
		aboutUsGames: { path: "detroitBecomeHuman.jpg", alt: "Логотип Detroit: Become Human" }
	},
	{
		_id: "21spark567gfhfgdayzzzzzzz",
		title: "DayZ",
		rate: 9.4,
		country: "CZ",
		imageMiddle: "dayzMiddle.jpg",
		altImageMiddle: "Выживший стоит на дороге",
		tags: ["Выживание", "Шутер", "action", "Постапокалипсис"],
		price: 877,
		platform: ["windows.svg"],
		iconForTitle: "zombieHead.svg",
		iconForTitleAlt: "Голова зомби",
		subTitle: "О! Враждебный мир",
		aboutUsGames: { path: "dayz.jpg", alt: "Логотип dayz" }
	},
	{
		_id: "21spark567gfhfgmadisonhor",
		title: "MADiSON",
		rate: 0.0,
		country: "AR",
		imageMiddle: "madisonMiddle.jpeg",
		altImageMiddle: "Рука чудовища над фотоаппаратом",
		tags: ["Психологический хоррор", "Хоррор", "Хоррор на выживание"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "ghost.svg",
		iconForTitleAlt: "Чудовище в халате",
		subTitle: "Не включай вспышку!",
		aboutUsGames: { path: "madison.jpg", alt: "Логотип MADiSON" }
	},
	{
		_id: "21spark567gfhfyoungiiiii",
		title: "Young Souls",
		rate: 0.0,
		country: "FR",
		imageMiddle: "youngSoulsMiddle.jpg",
		altImageMiddle: "Постер игры: главные герои и враги за их спинами",
		tags: ["action", "RPG"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "hero.svg",
		iconForTitleAlt: "Иконка героя",
		subTitle: "Стань борцом за справедливость",
		aboutUsGames: { path: "youngSouls.jpg", alt: "Логотип Young Souls" }
	},
	{
		_id: "21spark567gfhfhyperbolica546",
		title: "HYPERBOLICA",
		rate: 0.0,
		country: "US",
		imageMiddle: "hyperbolicaMiddle.jpeg",
		altImageMiddle: "Мир hyperbolica",
		tags: ["Фэнтези", "Приключения", "Логическая"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg", "vr.svg"],
		iconForTitle: "abstractionCube.svg",
		iconForTitleAlt: "Иконка абстрактного куба",
		subTitle: "Мир чудес",
		aboutUsGames: { path: "hyperbolica.jpg", alt: "HYPERBOLICA логотип на фоне Земли" }
	},
	{
		_id: "21spark567patfinderdfgdfg435345",
		title: "Pathfinder: Wrath of the Righteous",
		rate: 5.2,
		country: "RU",
		imageMiddle: "pathfinderWrathOfTheRighteousMiddle.jpg",
		altImageMiddle: "Ведьма из игры на постере",
		tags: ["Ролевая игра", "RPG"],
		price: 1124,
		oldPrice: 1499,
		sale: 25,
		platform: ["windows.svg", "apple.svg"],
		iconForTitle: "witch.svg",
		iconForTitleAlt: "Дом ведьмы",
		subTitle: "Если долго вглядываться в темноту, можно увидеть свет",
		aboutUsGames: { path: "pathfinder.jpg", alt: "Pathfinder: Wrath of the Righteous логотип" }
	},
	{
		_id: "21spark567gfhfdistantworld435",
		title: "Distant Worlds 2",
		rate: 0.0,
		country: "US",
		imageMiddle: "distantWorlds2Middle.jpg",
		altImageMiddle: "Космическая битва",
		tags: ["Симулятор", "стратегия"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "spacePlants.svg",
		iconForTitleAlt: "Планеты в космосе",
		subTitle: "Борозди просторы и укрепи альянс",
		aboutUsGames: { path: "distantWorlds2.jpg", alt: "Логотип Distant Worlds 2 на фоне космоса" }
	},
	{
		_id: "21spark567ruin",
		title: "RUiN",
		rate: 0.0,
		country: "SE",
		imageMiddle: "ruinMiddle.jpg",
		altImageMiddle: "Персонаж из игры передвигается по карте",
		tags: ["MOBA", "стратегия"],
		price: "ОЖИДАНИЕ",
		platform: ["windows.svg"],
		iconForTitle: "moba.svg",
		iconForTitleAlt: "Иконка специфики MOBA - карта",
		subTitle: "Арена ждет тебя!",
		aboutUsGames: { path: "ruin.jpg", alt: "Персонаж из игры RuIN" }
	},
	{
		_id: "21spark567warhammmm",
		title: "Warhammer: Vermintide 2",
		rate: 8.3,
		country: "SE",
		imageMiddle: "warhammerVermintide2Middle.jpg",
		altImageMiddle: "Орк из игры в доспехах",
		tags: ["Шутер", "action"],
		price: 103,
		oldPrice: 515,
		sale: 65,
		platform: ["windows.svg"],
		iconForTitle: "orc.svg",
		iconForTitleAlt: "Морда орка - иконка",
		subTitle: "Осторожно топор!!!!",
		aboutUsGames: { path: "warhammerVer2.png", alt: "Логотип Warhammer: Vermintide 2" }
	}
]

export default function getGamesCollectionMiddle() {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve(videoGamesCollectionMiddle)
		}, 1500)
	})
}